language: java
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_deploy:
  - ./gradlew build
deploy:
  - provider: releases
    api_key:
      secure: "HKAKvocbjLMxo8rNhz4grBE/DgFqeQMFo+5D1eCKX6ULqpTQXn8bFAn3jBbOk9dmwFkqm+B1vN9XASOVIdHt2tfftMP4oAuL8gGThJlo1rwZxhDoKxP4Er427/Uf/T134HOZxuRHT68DaULHoVmzuuEND/bqjWETwvR9/LJ5Od+1l2lMNwbGsqoYjaOCDMYnY5W2mtJvOBk5ALgy8ycDR1hRRUgDQ1Q9nAPDFOfK7u8Gd/Q2XFzJTS8NumkYugH/HP5lJE1XbkU78kqntv8k0KoY9y4+jfEN40IiaQdgU/UUgOumST8TMBKZtRSOKSXuK7s1PCsTkB4AyrPepsPgWD9c+ikgtmcsMUhqiIwJ3E6ZJ/Gs1ra8MG9b/CQSKwwUKLhluCpNarEZCEd2CIyUt8RBgO04abR3wvT71YCJiYVlokZoVMjhdDFp11GqKsMRN100BKXBZ12PsD28p+cx+EjBXDeb8Eoi08rCKEtG7KJ61ygXF15Okbb2ZOYibkUDQu/0tGwG4Xz1EG6P9Zx95ISDNR98LK7T6zMvvW1E+Da+ZqfN1B4uyT3rM+o5IRpbyze9bgcxCLLuScvkhedE0cQzD5SPlZZDu9xAVx2q8gYBPEbiIgeKi+7VjSKwEE1JjI9WHJF+NVbgQiGArTMxRZkSa3iIqBHtx1+ScP/ton8="
    file: "dist/ontology.jar"
    skip_cleanup: true
    on:
      tags: true
